language: scala
scala:
  - 2.12.0
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
    - $HOME/.ivy2
script:
  - sbt ++$TRAVIS_SCALA_VERSION '; scalastyle; coverage; test'
after_success:
  - sbt ++$TRAVIS_SCALA_VERSION coverageReport
  - sbt ++$TRAVIS_SCALA_VERSION codacyCoverage
